---
# handlers file for vector-role
# handlers для старта/рестарта сервиса Vector
- name: Restart Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
  when: use_systemd

- name: Reload systemd and restart Vector
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
    daemon_reload: true
  when: use_systemd